[package]
name = "toy_js_bundler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rslint_parser = "0.3.1"
path-absolutize = "3.0.13"
npm_rs = "0.2.1"
